var example_json = [
  {
    type: "ControlledVoltage",
    id: "ebfb35bb-5767-8155-c804-14bda7759dc2",
    x: 312,
    y: 154,
    width: 50,
    height: 50,
    alpha: 1,
    angle: 0,
    userData: {},
    cssClass: "draw2d_shape_node_End",
    ports: [
      {
        type: "draw2d.HybridPort",
        id: "36fbc34b-81e4-7748-b00e-e8d6291dac4d",
        width: 10,
        height: 10,
        alpha: 1,
        selectable: false,
        draggable: true,
        angle: 0,
        userData: {},
        cssClass: "draw2d_HybridPort",
        bgColor: "rgba(79,104,112,1)",
        color: "rgba(27,27,27,1)",
        stroke: 1,
        dasharray: null,
        maxFanOut: 9007199254740991,
        name: "hybrid0",
        semanticGroup: "global",
        port: "draw2d.HybridPort",
        locator: "draw2d.layout.locator.InputPortLocator",
        locatorAttr: {},
      },
      {
        type: "draw2d.HybridPort",
        id: "f1c2a48b-cb16-d052-1c43-718f587b4523",
        width: 10,
        height: 10,
        alpha: 1,
        selectable: false,
        draggable: true,
        angle: 0,
        userData: {},
        cssClass: "draw2d_HybridPort",
        bgColor: "rgba(79,104,112,1)",
        color: "rgba(27,27,27,1)",
        stroke: 1,
        dasharray: null,
        maxFanOut: 9007199254740991,
        name: "hybrid1",
        semanticGroup: "global",
        port: "draw2d.HybridPort",
        locator: "draw2d.layout.locator.OutputPortLocator",
        locatorAttr: {},
      },
    ],
    bgColor: "#FFFFFF",
    color: "#FFFFFF",
    stroke: 1,
    radius: 2,
    dasharray: null,
    labels: [
      {
        type: "draw2d.shape.basic.Label",
        id: "db69a8ab-a63b-f4f3-c025-5fae6b370790",
        x: -5.7578125,
        y: -23,
        width: 67.25,
        height: 21,
        alpha: 1,
        angle: 0,
        userData: {},
        cssClass: "draw2d_shape_basic_Label",
        ports: [],
        bgColor: "none",
        color: "#1B1B1B",
        stroke: 1,
        radius: 0,
        dasharray: null,
        text: "My top Label",
        outlineStroke: 0,
        outlineColor: "none",
        fontSize: 9,
        fontColor: "#080808",
        fontFamily: null,
        locator: "draw2d.layout.locator.TopLocator",
        editor: "draw2d.ui.LabelInplaceEditor",
      },
    ],
  },
];
